# Timezone
system_timezone: "Europe/Zurich"

# Firewall zones
internal_zone: "internal"
dmz_zone: "dmz"

# Monitoring server
monitoring_server: "192.168.1.25"

# Database credentials (reference vault variables)
trackify_db_name: "trackify"
trackify_db_user: "trackify_user"
