---
# Keycloak IAM configuration
keycloak_monitoring_enabled: true
keycloak_ssl_enabled: false  # SSL terminated at Traefik
keycloak_metrics_enabled: true
keycloak_health_enabled: true

# Performance tuning
keycloak_jvm_heap_min: "512m"
keycloak_jvm_heap_max: "1024m"
keycloak_jvm_metaspace: "256m"

# Proxy configuration for Traefik
keycloak_proxy_mode: "edge"
keycloak_proxy_headers: true
keycloak_hostname_strict: false

# Theme and branding
keycloak_default_theme: "keycloak"
keycloak_admin_theme: "keycloak"

# Security settings
keycloak_security_headers_enabled: true
keycloak_csrf_protection_enabled: true

# Firewall configuration
keycloak_configure_firewall: true
keycloak_firewall_zone: "internal"