
---
- name: Create PostgreSQL databases with effective locale
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('UTF8') }}"
    lc_collate: "{{ postgresql_effective_locale | default('C') }}"
    lc_ctype: "{{ postgresql_effective_locale | default('C') }}"
    template: "{{ item.template | default('template0') }}"
    state: present
  become_user: postgres
  loop: "{{ postgresql_databases }}"
  tags: postgresql_databases

- name: Create PostgreSQL users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    db: "{{ item.db | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    expires: "{{ item.expires | default('infinity') }}"
    state: present
  become_user: postgres
  loop: "{{ postgresql_users }}"
  no_log: true
  tags: postgresql_databases

- name: Grant database privileges to users
  postgresql_privs:
    db: "{{ item.db }}"
    privs: "{{ item.priv }}"
    type: database
    obj: "{{ item.db }}"
    role: "{{ item.name }}"
    state: present
  become_user: postgres
  loop: "{{ postgresql_users }}"
  when: item.db is defined and item.priv is defined
  tags: postgresql_databases