
---
- name: Download PostgreSQL Exporter
  get_url:
    url: "{{ postgresql_exporter_download_url }}"
    dest: /tmp/postgres_exporter.tar.gz
    mode: '0644'
  tags: postgresql_monitoring

- name: Extract PostgreSQL Exporter
  unarchive:
    src: /tmp/postgres_exporter.tar.gz
    dest: /tmp
    remote_src: yes
  tags: postgresql_monitoring

- name: Copy PostgreSQL Exporter binary
  copy:
    src: "/tmp/postgres_exporter-{{ postgresql_exporter_version }}.linux-amd64/postgres_exporter"
    dest: "{{ postgresql_exporter_binary_path }}"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  tags: postgresql_monitoring

- name: Create postgres_exporter user
  user:
    name: "{{ postgresql_exporter_user }}"
    system: yes
    shell: /bin/false
    home: /nonexistent
    create_home: no
  tags: postgresql_monitoring

- name: Create monitoring user in PostgreSQL
  postgresql_user:
    name: "{{ postgresql_exporter_user }}"
    password: "{{ postgresql_exporter_password }}"
    role_attr_flags: LOGIN
    state: present
  become_user: postgres
  tags: postgresql_monitoring

- name: Grant monitoring privileges to exporter user
  postgresql_privs:
    db: postgres
    privs: CONNECT
    type: database
    obj: postgres
    role: "{{ postgresql_exporter_user }}"
    state: present
  become_user: postgres
  tags: postgresql_monitoring

- name: Create PostgreSQL Exporter environment file
  template:
    src: postgres_exporter.env.j2
    dest: "{{ postgresql_exporter_config_path }}"
    mode: '0600'
    owner: "{{ postgresql_exporter_user }}"
    group: "{{ postgresql_exporter_user }}"
  notify: restart postgres_exporter
  tags: postgresql_monitoring

- name: Create PostgreSQL Exporter systemd service
  template:
    src: postgres_exporter.service.j2
    dest: "{{ postgresql_exporter_service_path }}"
    mode: '0644'
  notify: restart postgres_exporter
  tags: postgresql_monitoring

- name: Start and enable PostgreSQL Exporter
  systemd:
    name: postgres_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  tags: postgresql_monitoring