
---
- name: Clone Trackify repository
  git:
    repo: "{{ trackify_git_repo }}"
    dest: "{{ trackify_source_dir }}"
    version: "{{ trackify_git_branch }}"
    force: yes
    depth: 1
  become_user: "{{ nginx_user }}"
  tags: nginx_build

- name: Set correct ownership of source directory
  file:
    path: "{{ trackify_source_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    recurse: yes
  tags: nginx_build

- name: Install npm dependencies
  npm:
    path: "{{ trackify_source_dir }}"
    state: present
    production: "{{ trackify_production_build }}"
  become_user: "{{ nginx_user }}"
  environment:
    NODE_ENV: "{{ 'production' if trackify_production_build else 'development' }}"
  tags: nginx_build

- name: Build React application
  command: npm run build
  args:
    chdir: "{{ trackify_source_dir }}"
  become_user: "{{ nginx_user }}"
  environment:
    NODE_ENV: "{{ 'production' if trackify_production_build else 'development' }}"
    CI: "true"
  register: build_result
  changed_when: true
  tags: nginx_build

- name: Display build output
  debug:
    var: build_result.stdout_lines
  when: build_result.stdout_lines is defined
  tags: nginx_build

- name: Remove existing build files in web directory
  file:
    path: "{{ trackify_web_root }}"
    state: absent
  tags: nginx_build

- name: Create web root directory
  file:
    path: "{{ trackify_web_root }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0755'
  tags: nginx_build

- name: Copy built application to web root
  copy:
    src: "{{ trackify_source_dir }}/{{ trackify_build_dir }}/client/"
    dest: "{{ trackify_web_root }}/"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
    remote_src: yes
  tags: nginx_build

- name: Set correct permissions for web files
  file:
    path: "{{ trackify_web_root }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
    recurse: yes
  tags: nginx_build

- name: Set execute permissions for directories
  find:
    paths: "{{ trackify_web_root }}"
    file_type: directory
  register: web_directories
  tags: nginx_build

- name: Apply directory permissions
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ web_directories.files }}"
  tags: nginx_build