
---
- name: Configure firewall for NGINX HTTP
  firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    zone: public
    immediate: yes
  become: true
  notify: reload firewalld
  tags: nginx_firewall