---
collections:
  - name: community.postgresql
    version: ">=2.0.0"
  - name: community.general
    version: ">=5.0.0"
  - name: community.proxmox
    version: ">=1.0.0"
  - name: ansible.posix
    version: ">=1.0.0"
  - name: community.crypto
    version: ">=1.0.0"