
---
# Basic nginx configuration
nginx_user: nginx
nginx_group: nginx
nginx_home_dir: /var/lib/nginx
nginx_conf_dir: /etc/nginx
nginx_log_dir: /var/log/nginx
nginx_cache_dir: /var/cache/nginx
nginx_pid_dir: /var/run

# Service configuration
nginx_configure_firewall: true
nginx_selinux_enabled: true

# Performance tuning
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_keepalive_timeout: 65
nginx_client_max_body_size: 64m
nginx_server_tokens: false
nginx_gzip_enabled: true

# Document roots to create
nginx_document_roots:
  - /var/www/html
  - "{{ trackify_web_root }}"

# Node.js configuration
nodejs_version: "20"
nodejs_packages:
  - nodejs
  - npm
  - gcc-c++
  - make
  - git

nodejs_global_packages:
  - yarn

# Trackify application configuration
trackify_git_repo: "https://github.com/bbzbl-it-joku/Module306-Frontend.git"  # Update with actual repo
trackify_source_dir: /opt/trackify-frontend
trackify_web_root: /var/www/trackify
trackify_build_dir: "build"  # or "dist" depending on your build setup

# Branch selection based on inventory hostname
trackify_git_branch: "{{ 'dev' if inventory_hostname.startswith('dev') else 'main' }}"
trackify_production_build: "{{ not inventory_hostname.startswith('dev') }}"

# Logging configuration
nginx_access_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for" "$request_time"'

nginx_error_log_level: warn
