---
# Keycloak version and basic configuration
keycloak_version: "23.0.0"
keycloak_user: keycloak
keycloak_group: keycloak
keycloak_home_dir: /opt/keycloak
keycloak_config_dir: /opt/keycloak/conf
keycloak_data_dir: /opt/keycloak/data
keycloak_log_dir: /var/log/keycloak

# Java configuration
java_version: "21"
java_package: "java-21-openjdk-headless"

# Network configuration
keycloak_bind_address: "0.0.0.0"
keycloak_port: 8080
keycloak_ssl_port: 8443
keycloak_hostname: "{{ inventory_hostname }}.jokulab.ch:{{ keycloak_port }}"
keycloak_hostname_strict: false
keycloak_hostname_strict_https: false

# Database configuration
keycloak_db_vendor: "postgres"
keycloak_db_host: "{{ 'dev' if inventory_hostname.startswith('dev') else 'prd' }}db01.jokulab.ch"
keycloak_db_port: 5432
keycloak_db_name: "keycloak"
keycloak_db_user: "keycloak_user"
keycloak_db_password: "{{ keycloak_db_password | default('changeme') }}"
keycloak_db_schema: "public"

# Admin user configuration
keycloak_admin_user: "admin"
keycloak_admin_password: "{{ keycloak_admin_password | default('admin') }}"

# SSL/TLS configuration
keycloak_ssl_enabled: false
keycloak_ssl_keystore: "{{ keycloak_config_dir }}/keycloak.p12"
keycloak_ssl_keystore_password: "{{ keycloak_keystore_password | default('changeme') }}"
keycloak_ssl_key_alias: "keycloak"

# JVM configuration
keycloak_jvm_heap_min: "512m"
keycloak_jvm_heap_max: "1024m"
keycloak_jvm_metaspace: "256m"
keycloak_jvm_opts: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:+OptimizeStringConcat"

# Cache configuration (Updated for Keycloak 23+)
keycloak_cache_stack: "local"  # Options: ispn (Infinispan), local
keycloak_cache_enabled: false 

# Logging configuration
keycloak_log_level: "INFO"
keycloak_root_log_level: "WARN"
keycloak_access_log_enabled: true

# Metrics and monitoring
keycloak_metrics_enabled: true
keycloak_health_enabled: true

# Security configuration
keycloak_security_headers_enabled: true
keycloak_csrf_protection_enabled: true

# Proxy configuration (for use behind Traefik)
keycloak_proxy_mode: "edge"  # Options: edge, reencrypt, passthrough
keycloak_proxy_headers: true

# Theme configuration
keycloak_default_theme: "keycloak"
keycloak_admin_theme: "keycloak"

# Realm configuration
keycloak_realms:
  - name: "trackify"
    display_name: "Trackify Application"
    enabled: true
    default_locale: "en"
    login_theme: "keycloak"
    admin_theme: "keycloak"
    account_theme: "keycloak"
    email_theme: "keycloak"

# Client configuration for Trackify
keycloak_clients:
  - client_id: "trackify-frontend"
    name: "Trackify Frontend Application"
    realm: "trackify"
    enabled: true
    public_client: true
    standard_flow_enabled: true
    direct_access_grants_enabled: false
    valid_redirect_uris:
      - "https://trackify.jokulab.ch/*"
      - "https://trackify-dev.jokulab.ch/*"
      - "http://localhost:3000/*"  # Development
    web_origins:
      - "https://trackify.jokulab.ch"
      - "https://trackify-dev.jokulab.ch"
      - "http://localhost:3000"

  - client_id: "trackify-backend"
    name: "Trackify Backend API"
    realm: "trackify"
    enabled: true
    public_client: false
    service_accounts_enabled: true
    authorization_services_enabled: true
    standard_flow_enabled: false
    direct_access_grants_enabled: true

# User configuration
keycloak_users:
  - username: "admin"
    email: "admin@trackify.local"
    first_name: "System"
    last_name: "Administrator"
    realm: "trackify"
    password: "{{ trackify_admin_password | default('admin123') }}"
    roles:
      - "admin"
      - "user"

# Role configuration
keycloak_roles:
  - name: "admin"
    realm: "trackify"
    description: "Administrator role with full access"
  - name: "user"
    realm: "trackify"
    description: "Standard user role"
  - name: "viewer"
    realm: "trackify"
    description: "Read-only access role"

# Firewall configuration
keycloak_configure_firewall: true
keycloak_firewall_zone: "internal"

# Service configuration
keycloak_service_enabled: true
keycloak_service_state: "started"
