
---
- name: restart spring-boot
  systemd:
    name: "{{ spring_boot_service_name }}"
    state: restarted
    daemon_reload: yes
  listen: "restart spring-boot"

- name: reload spring-boot
  systemd:
    name: "{{ spring_boot_service_name }}"
    state: reloaded
  listen: "reload spring-boot"

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  listen: "reload firewalld"

- name: restore selinux contexts
  command: restorecon -R {{ item }}
  loop:
    - "{{ spring_boot_app_dir }}"
    - "{{ spring_boot_config_dir }}"
    - "{{ spring_boot_log_dir }}"
  when: ansible_selinux.status == "enabled"
  listen: "restore selinux contexts"
