---
# Basic Traefik configuration
traefik_version: "3.0.4"
traefik_user: traefik
traefik_group: traefik
traefik_home_dir: /var/lib/traefik

# Directories
traefik_config_dir: /etc/traefik
traefik_data_dir: /var/lib/traefik
traefik_log_dir: /var/log/traefik
traefik_ssl_dir: /etc/traefik/ssl
traefik_dynamic_config_dir: /etc/traefik/dynamic
traefik_binary_path: /usr/local/bin/traefik

# Domain configuration
traefik_domain: "jokulab.ch"
traefik_trackify_subdomain: "trackify"
traefik_trackify_dev_subdomain: "trackify-dev"

# Network configuration
traefik_entrypoints:
  web:
    address: ":80"
    redirect_to_https: true
  websecure:
    address: ":443"

# Dashboard configuration
traefik_dashboard_enabled: false
traefik_dashboard_port: 8088
traefik_dashboard_auth_enabled: true
traefik_dashboard_user: admin
traefik_dashboard_password: "{{ vault_traefik_dashboard_password | default('changeme') }}"
traefik_dashboard_domain: "traefik.{{ traefik_domain }}"

# SSL/TLS configuration
traefik_ssl_enabled: true
traefik_letsencrypt_enabled: true
traefik_letsencrypt_staging: false  # Set to true for testing
traefik_letsencrypt_email: "admin@{{ traefik_domain }}"
traefik_generate_selfsigned_cert: false  # Disabled when using DNS challenge

# DNS Challenge configuration
traefik_dns_challenge_enabled: true
traefik_dns_provider: "cloudflare"  # DNS provider to use
traefik_dns_resolvers:
  - "1.1.1.1:53"
  - "8.8.8.8:53"

# Cloudflare specific settings
traefik_cloudflare_api_token: "{{ vault_cloudflare_api_token | default('') }}"
traefik_cloudflare_zone_api_token: "{{ vault_cloudflare_zone_api_token | default('') }}"
traefik_cloudflare_dns_api_token: "{{ vault_cloudflare_dns_api_token | default('') }}"

# Legacy Cloudflare settings (fallback)
traefik_cloudflare_email: "{{ vault_cloudflare_email | default('') }}"
traefik_cloudflare_api_key: "{{ vault_cloudflare_api_key | default('') }}"

# Challenge preference: dns or http
traefik_challenge_method: "dns"  # Options: dns, http

# Service discovery and routing
traefik_backend_services:
  # Frontend service (NGINX)
  trackify-frontend:
    domain: "{{ traefik_trackify_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://prdweb01.jokulab.ch:80"
    health_check: "/health"
    
  trackify-frontend-dev:
    domain: "{{ traefik_trackify_dev_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://devweb01.jokulab.ch:80"
    health_check: "/health"
    
  # API service (Spring Boot)
  trackify-api:
    domain: "{{ traefik_trackify_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://prdapp01.jokulab.ch:8080"
    path_prefix: "/api"
    health_check: "/api/health"
    strip_prefix: false
    
  trackify-api-dev:
    domain: "{{ traefik_trackify_dev_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://devapp01.jokulab.ch:8080"
    path_prefix: "/api"
    health_check: "/api/health"
    strip_prefix: false

  # Keycloak Identity and Access Management (Production)
  trackify-keycloak:
    domain: "keycloak.{{ traefik_trackify_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://prdkc01.jokulab.ch:8080"
    health_check: "/health/ready"
    strip_prefix: false
    priority: 100  # Higher priority for auth routes
    middlewares:
      - "keycloak-headers"
      - "keycloak-cors"
    
  # Keycloak Identity and Access Management (Development)
  trackify-keycloak-dev:
    domain: "keycloak.{{ traefik_trackify_dev_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://devkc01.jokulab.ch:8080"
    health_check: "/health/ready"
    strip_prefix: false
    priority: 100  # Higher priority for auth routes
    middlewares:
      - "keycloak-headers"
      - "keycloak-cors"

  # MinIO Object Storage API (Production) - for direct file access
  trackify-minio-api:
    domain: "{{ traefik_trackify_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://prds301.jokulab.ch:9000"
    path_prefix: "/files"
    health_check: "/minio/health/ready"
    strip_prefix: true
    
  # MinIO Object Storage API (Development) - for direct file access  
  trackify-minio-api-dev:
    domain: "{{ traefik_trackify_dev_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://devs301.jokulab.ch:9000"
    path_prefix: "/files"
    health_check: "/minio/health/ready"
    strip_prefix: true

  # MinIO Object Storage Console (Production)
  trackify-minio:
    domain: "{{ traefik_trackify_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://prds301.jokulab.ch:9001"
    path_prefix: "/minio"
    health_check: "/minio/health/live"
    strip_prefix: true
    
  # MinIO Object Storage Console (Development)
  trackify-minio-dev:
    domain: "{{ traefik_trackify_dev_subdomain }}.{{ traefik_domain }}"
    backend_url: "http://devs301.jokulab.ch:9001"
    path_prefix: "/minio"
    health_check: "/minio/health/live"
    strip_prefix: true

# Logging configuration
traefik_log_level: INFO
traefik_access_log_enabled: true
traefik_access_log_file: "{{ traefik_log_dir }}/access.log"
traefik_log_file: "{{ traefik_log_dir }}/traefik.log"

# Security configuration
traefik_security_headers:
  frameDeny: true
  contentTypeNosniff: true
  browserXssFilter: true
  referrerPolicy: "strict-origin-when-cross-origin"
  forceSTSHeader: true
  stsIncludeSubdomains: true
  stsPreload: true
  stsSeconds: 31536000

# Keycloak-specific security headers
traefik_keycloak_headers:
  customRequestHeaders:
    X-Forwarded-Proto: "https"
    X-Forwarded-Host: "keycloak.{{ traefik_trackify_subdomain }}.{{ traefik_domain }}"
    X-Forwarded-Port: "443"
  customResponseHeaders:
    X-Content-Type-Options: "nosniff"
    Referrer-Policy: "strict-origin-when-cross-origin"

# Rate limiting
traefik_rate_limit_enabled: true
traefik_rate_limit_burst: 100
traefik_rate_limit_average: 50

# Keycloak-specific rate limiting (more lenient for auth)
traefik_keycloak_rate_limit:
  burst: 200
  average: 100

# Monitoring
traefik_metrics_enabled: true
traefik_metrics_prometheus_enabled: true

# Firewall configuration
traefik_configure_firewall: true
traefik_firewall_zone: dmz
traefik_selinux_enabled: true

# Path-based routing configuration
traefik_keycloak_paths:
  auth: "/auth"
  admin: "/admin"
  health: "/health"