
---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  listen: "restart nginx"

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  listen: "reload nginx"

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  listen: "reload firewalld"
