
---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  listen: "restart nginx"

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  listen: "reload nginx"

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  listen: "reload firewalld"

- name: restore selinux contexts
  command: restorecon -R {{ item }}
  loop:
    - "/var/www"
    - "{{ trackify_web_root }}"
  when: ansible_selinux.status == "enabled"
  listen: "restore selinux contexts"