---
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart keycloak
  systemd:
    name: "{{ keycloak_service_name }}"
    state: restarted
    enabled: yes
  become: true

- name: start keycloak
  systemd:
    name: "{{ keycloak_service_name }}"
    state: started
    enabled: yes
  become: true

- name: stop keycloak
  systemd:
    name: "{{ keycloak_service_name }}"
    state: stopped
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true