
---
# Internal variables (should not be overridden)
spring_boot_packages:
  - git
  - curl
  - wget

# Java configuration
java_home_path: "/usr/lib/jvm/java-{{ java_version }}-openjdk"

# Maven configuration
maven_download_url: "https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
maven_opts: "-Xmx1024m -XX:ReservedCodeCacheSize=512m"
