---
# Development Keycloak server configuration
keycloak_jvm_heap_min: "512m"
keycloak_jvm_heap_max: "1024m"
keycloak_jvm_metaspace: "256m"

# Database configuration
keycloak_db_host: "devdb01.jokulab.ch"
keycloak_db_port: 5432
keycloak_db_name: "keycloak"
keycloak_db_user: "keycloak_user"
keycloak_db_password: "{{ keycloak_db_password | default('keycloak123') }}"

# Development hostname (IMPORTANT: Remove port from hostname)
keycloak_hostname: "devkc01.jokulab.ch"

# Proxy configuration for Traefik
keycloak_proxy_mode: "edge"
keycloak_proxy_headers: true
keycloak_hostname_strict: false

# Reduced logging for development
keycloak_log_level: "INFO"  # Changed from DEBUG to INFO

# Cache configuration simplified
keycloak_cache_stack: "local"

# Development-specific realm configuration
keycloak_realms:
  - name: "trackify-dev"
    display_name: "Trackify Development"
    enabled: true
    default_locale: "en"

# Development client configuration
keycloak_clients:
  - client_id: "trackify-frontend-dev"
    name: "Trackify Frontend Development"
    realm: "trackify-dev"
    enabled: true
    public_client: true
    standard_flow_enabled: true
    direct_access_grants_enabled: false
    valid_redirect_uris:
      - "https://trackify-dev.jokulab.ch/*"
      - "http://localhost:3000/*"
    web_origins:
      - "https://trackify-dev.jokulab.ch"
      - "http://localhost:3000"

  - client_id: "trackify-backend-dev"
    name: "Trackify Backend Development"
    realm: "trackify-dev"
    enabled: true
    public_client: false
    service_accounts_enabled: true
    standard_flow_enabled: false
    direct_access_grants_enabled: "refreshTokenMaxReuse"