
---
# PostgreSQL version and basic configuration
postgresql_version: "14"
postgresql_port: 5432
postgresql_data_dir: "/var/lib/pgsql/{{ postgresql_version }}/data"
postgresql_config_dir: "/var/lib/pgsql/{{ postgresql_version }}/data"
postgresql_log_dir: "/var/log/postgresql"

# Database configuration with safe locale defaults
postgresql_databases:
  - name: "{{ trackify_db_name | default('trackify') }}"
    encoding: "UTF8"
    lc_collate: "{{ postgresql_locale | default('C') }}"
    lc_ctype: "{{ postgresql_locale | default('C') }}"

postgresql_users:
  - name: "{{ trackify_db_user | default('trackify_user') }}"
    password: "{{ trackify_db_password }}"
    db: "{{ trackify_db_name | default('trackify') }}"
    priv: "ALL"
    expires: "infinity"

# Locale configuration
postgresql_locale: "C"  # Safe default that works everywhere
postgresql_locale_utf8: "en_US.utf8"  # Will be detected and used if available

# Performance tuning defaults
postgresql_max_connections: 200
postgresql_shared_buffers: "256MB"
postgresql_effective_cache_size: "1GB"
postgresql_work_mem: "4MB"
postgresql_maintenance_work_mem: "64MB"
postgresql_wal_buffers: "16MB"
postgresql_max_wal_size: "1GB"
postgresql_min_wal_size: "80MB"
postgresql_checkpoint_completion_target: 0.9
postgresql_checkpoint_timeout: "5min"
postgresql_random_page_cost: 1.1
postgresql_effective_io_concurrency: 200

# Logging configuration
postgresql_log_destination: "stderr"
postgresql_logging_collector: true
postgresql_log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
postgresql_log_rotation_age: "1d"
postgresql_log_rotation_size: "10MB"
postgresql_log_min_duration_statement: 1000
postgresql_log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
postgresql_log_lock_waits: true
postgresql_log_statement: "ddl"
postgresql_log_temp_files: 0

# Authentication and security
postgresql_listen_addresses: "*"
postgresql_password_encryption: "scram-sha-256"
postgresql_ssl: false
postgresql_ssl_cert_file: ""
postgresql_ssl_key_file: ""
postgresql_ssl_ca_file: ""

# Backup configuration
postgresql_backup_enabled: true
postgresql_backup_dir: "/backup/postgresql"
postgresql_backup_retention_days: 30
postgresql_backup_time: "02:00"

# Monitoring configuration
postgresql_monitoring_enabled: true
postgresql_exporter_version: "0.12.0"
postgresql_exporter_port: 9187
postgresql_exporter_user: "postgres_exporter"

# Network and firewall
postgresql_firewall_enabled: true
postgresql_internal_networks:
  - "192.168.1.0/24"
postgresql_dmz_networks:
  - "192.168.100.0/24"

# Autovacuum settings
postgresql_autovacuum: true
postgresql_autovacuum_max_workers: 3
postgresql_autovacuum_naptime: "1min"
postgresql_autovacuum_vacuum_threshold: 50
postgresql_autovacuum_vacuum_scale_factor: 0.2
postgresql_autovacuum_analyze_threshold: 50
postgresql_autovacuum_analyze_scale_factor: 0.1
