---
- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: restart minio
  systemd:
    name: minio
    state: restarted
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  listen: "reload firewalld"
  become: true