---
- name: Check Disk Size
  hosts: "{{ hostname }}"

  tasks:
    - name: Gather disk facts
      ansible.builtin.setup:
        filter: ansible_mounts
      register: disk_facts

    - name: Display disk size
      ansible.builtin.debug:
        msg: "Mount {{ item.mount }} has {{ (item.size_total | int / 1024 / 1024 / 1024) | round(2) }} GB total and {{ (item.size_available | int / 1024 / 1024 / 1024) | round(2) }} GB available"
      loop: "{{ ansible_mounts }}"