---
- name: Simple disk extension for LVM setup
  hosts: "{{ hostname }}"
  become: true
  gather_facts: true

  tasks:
    - name: Show current disk usage
      shell: df -h /
      register: current_usage
      changed_when: false

    - name: Display current usage
      debug:
        var: current_usage.stdout_lines

    - name: Get primary disk name
      shell: lsblk -no PKNAME $(df / | tail -1 | awk '{print $1}') | head -1
      register: root_disk
      changed_when: false

    - name: Get last partition number on root disk
      shell: "lsblk -no NAME /dev/{{ root_disk.stdout }} | grep -E '[0-9]$' | tail -1 | grep -o '[0-9]*$'"
      register: last_partition_num
      changed_when: false

    - name: Set partition device name
      set_fact:
        partition_device: "/dev/{{ root_disk.stdout }}{{ last_partition_num.stdout }}"
        disk_device: "/dev/{{ root_disk.stdout }}"

    - name: Show what we found
      debug:
        msg: "Working with disk {{ disk_device }}, partition {{ partition_device }}"

    - name: Check for unallocated space
      shell: "parted {{ disk_device }} print free | grep -i 'free space' | wc -l"
      register: free_space_count
      changed_when: false

    - name: Extend partition if there's free space
      block:
        - name: Extend partition to use all space
          shell: "parted {{ disk_device }} ---pretend-input-tty resizepart {{ last_partition_num.stdout }} Yes 100%"
          
        - name: Inform kernel of partition table changes
          shell: "partprobe {{ disk_device }}"
          
        - name: Wait a moment for changes to settle
          pause:
            seconds: 2
            
      when: free_space_count.stdout | int > 0

    - name: Extend LVM physical volume
      shell: "pvresize {{ partition_device }}"
      when: free_space_count.stdout | int > 0

    - name: Extend logical volume (root)
      shell: "lvextend -l +100%FREE /dev/vg_root/lv_root"
      register: lv_extend
      failed_when: 
        - lv_extend.rc != 0
        - "'matches existing size' not in lv_extend.stderr"

    - name: Detect filesystem type
      shell: "mount | grep ' / ' | awk '{print $5}'"
      register: fs_type
      changed_when: false

    - name: Extend XFS filesystem
      shell: "xfs_growfs /"
      when: 
        - fs_type.stdout == "xfs"
        - lv_extend is changed

    - name: Extend EXT filesystem
      shell: "resize2fs /dev/vg_root/lv_root"
      when: 
        - fs_type.stdout in ["ext2", "ext3", "ext4"]
        - lv_extend is changed

    - name: Show final disk usage
      shell: df -h /
      register: final_usage
      changed_when: false

    - name: Display final usage
      debug:
        var: final_usage.stdout_lines

    - name: Show summary
      debug:
        msg: |
          Extension completed!
          - Filesystem type: {{ fs_type.stdout }}
          - Had free space to extend: {{ 'Yes' if free_space_count.stdout | int > 0 else 'No' }}
          - LV extended: {{ 'Yes' if lv_extend is changed else 'No space to extend' }}