---
- name: Extend partition and volume group on AlmaLinux 9
  hosts: "{{ hostname }}"
  become: true
  vars:
    disk_device: /dev/sda
    partition_number: 3
    vg_name: vg_root
    lv_name: lv_root
    
  tasks:
    - name: Install required packages
      dnf:
        name:
          - parted
          - lvm2
          - e2fsprogs
        state: present

    - name: Get current disk information
      command: lsblk {{ disk_device }} -o NAME,SIZE,FSTYPE,MOUNTPOINTS
      register: disk_info
      changed_when: false

    - name: Display current disk layout
      debug:
        msg: "{{ disk_info.stdout_lines }}"

    - name: Get current partition table info
      parted:
        device: "{{ disk_device }}"
        unit: MiB
      register: partition_info

    - name: Display current partition information
      debug:
        msg: "Current partitions: {{ partition_info.partitions }}"

    - name: Extend partition to use all available space
      parted:
        device: "{{ disk_device }}"
        number: "{{ partition_number }}"
        part_end: "100%"
        resize: true
        state: present
      register: partition_extended

    - name: Inform kernel about partition table changes
      command: partprobe {{ disk_device }}
      when: partition_extended.changed

    - name: Wait for partition to be available
      wait_for:
        path: "{{ disk_device }}{{ partition_number }}"
        timeout: 10
      when: partition_extended.changed

    - name: Get current PV information
      command: pvdisplay {{ disk_device }}{{ partition_number }}
      register: pv_info
      changed_when: false
      failed_when: pv_info.rc not in [0, 5]

    - name: Resize physical volume to use all partition space
      command: pvresize {{ disk_device }}{{ partition_number }}
      register: pv_resize_result
      when: partition_extended.changed

    - name: Get volume group information before extending
      command: vgdisplay {{ vg_name }}
      register: vg_info_before
      changed_when: false

    - name: Display VG free space before extending
      debug:
        msg: "VG {{ vg_name }} free space before: {{ vg_info_before.stdout | regex_search('Free  PE / Size\\s+([0-9]+\\s*/\\s*[0-9.]+\\s*[A-Za-z]+)', '\\1') }}"

    - name: Get current logical volume size
      command: lvdisplay /dev/{{ vg_name }}/{{ lv_name }}
      register: lv_info_before
      changed_when: false

    - name: Extend logical volume to use all available space in VG
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: +100%FREE
      register: lv_extended

    - name: Get filesystem type
      command: blkid -o value -s TYPE /dev/{{ vg_name }}/{{ lv_name }}
      register: fs_type
      changed_when: false

    - name: Extend XFS filesystem
      command: xfs_growfs /
      when: 
        - lv_extended.changed
        - fs_type.stdout == "xfs"

    - name: Extend ext4 filesystem
      command: resize2fs /dev/{{ vg_name }}/{{ lv_name }}
      when: 
        - lv_extended.changed
        - fs_type.stdout in ["ext4", "ext3", "ext2"]

    - name: Get final disk information
      command: lsblk {{ disk_device }} -o NAME,SIZE,FSTYPE,MOUNTPOINTS
      register: final_disk_info
      changed_when: false

    - name: Display final disk layout
      debug:
        msg: "{{ final_disk_info.stdout_lines }}"

    - name: Get final volume group information
      command: vgdisplay {{ vg_name }}
      register: vg_info_after
      changed_when: false

    - name: Display final VG information
      debug:
        msg: "Final VG {{ vg_name }} info: {{ vg_info_after.stdout | regex_search('VG Size\\s+([0-9.]+\\s*[A-Za-z]+)', '\\1') }}"

    - name: Get final filesystem usage
      command: df -h /
      register: df_info
      changed_when: false

    - name: Display filesystem usage
      debug:
        msg: "{{ df_info.stdout_lines }}"

    - name: Summary of changes
      debug:
        msg: |
          Extension completed successfully!
          - Partition {{ partition_number }} has been extended to use all available disk space
          - Physical Volume has been resized
          - Volume Group {{ vg_name }} now uses all available space
          - Logical Volume {{ lv_name }} has been extended
          - Filesystem has been grown to use the new space