
---
- name: Clone Trackify backend repository
  git:
    repo: "{{ trackify_backend_git_repo }}"
    dest: "{{ trackify_backend_source_dir }}"
    version: "{{ trackify_backend_git_branch }}"
    force: yes
    depth: 1
  become_user: "{{ spring_boot_user }}"
  tags: spring_boot_build

- name: Set correct ownership of source directory
  file:
    path: "{{ trackify_backend_source_dir }}"
    owner: "{{ spring_boot_user }}"
    group: "{{ spring_boot_group }}"
    recurse: yes
  tags: spring_boot_build

- name: Build Spring Boot application
  shell: |
    source /etc/profile.d/maven.sh
    mvn clean package {{ maven_build_opts }}
  args:
    chdir: "{{ trackify_backend_source_dir }}"
  become_user: "{{ spring_boot_user }}"
  environment:
    JAVA_HOME: "{{ java_home_path }}"
    MAVEN_OPTS: "{{ maven_opts }}"
  register: build_result
  changed_when: true
  tags: spring_boot_build

- name: Display build output
  debug:
    var: build_result.stdout_lines
  when: build_result.stdout_lines is defined
  tags: spring_boot_build

- name: Stop Spring Boot service before deployment
  systemd:
    name: "{{ spring_boot_service_name }}"
    state: stopped
  failed_when: false
  tags: spring_boot_build

- name: Copy built JAR to application directory
  copy:
    src: "{{ trackify_backend_source_dir }}/target/{{ trackify_backend_jar_name }}"
    dest: "{{ spring_boot_app_dir }}/{{ spring_boot_service_name }}.jar"
    owner: "{{ spring_boot_user }}"
    group: "{{ spring_boot_group }}"
    mode: '0755'
    remote_src: yes
  notify: restart spring-boot
  tags: spring_boot_build
