
---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: spring_boot

- name: Include installation tasks
  include_tasks: install.yml
  tags: spring_boot

- name: Include Java/Maven setup tasks
  include_tasks: java.yml
  tags: spring_boot

- name: Include application build tasks
  include_tasks: build.yml
  tags: spring_boot

- name: Include configuration tasks
  include_tasks: configure.yml
  tags: spring_boot

- name: Include service management tasks
  include_tasks: service.yml
  tags: spring_boot

- name: Include firewall configuration tasks
  include_tasks: firewall.yml
  tags: spring_boot
  when: spring_boot_configure_firewall
